service: message-chat

provider:
  name: aws
  runtime: python2.7


functions:
  send_message:
    handler: handler.post
    events:
      - http: post chat
  get_messages:
    handler: handler.get
    events:
      - http: get chat

resources:
  Resources:
    chatTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: chat_messages
        AttributeDefinitions:
          - AttributeName: message
            AttributeType: S
          - AttributeName: created
            AttributeType: N
        KeySchema:
          - AttributeName: message
            KeyType: HASH
          - AttributeName: created
            KeyType: RANGE
        ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
