service: chat

provider:
  name: aws
  runtime: python2.7


functions:
  send_message:
    handler: handler.post
    events:
      - http: post chat
  get_messages:
    handler: handler.get
    events:
      - http: get chat

resources:
  Resources:
    chatTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: messages
        AttributeDefinitions:
          - AttributeName: created
            AttributeType: N
        KeySchema:
          - AttributeName: created
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
